### ISSUE TITLE
The code is not support actual what you share in coding many parts either delete or hidden because many issues and error to implement no real result so .... unbeneficial 

### ISSUE THREAD

**Issue by 123alikaha** [groupJia/MedSharing2021#1]

**Comment by 1509769813** [comment]
你好，我想问一下这一部分/home/mwang235/Downloads/maildir文件去哪下？

**Comment by 123alikaha** [comment]
What kind of types of data do you utilize for the following files if it is possible just a short example or data set, please and I use the code it looks like there are some parts missing from your code please add more code if it missed any from [build_index.py], [constant_abe.py] and [read_data.py] files. The following data set is needed if possible please share. 

1. f_Kw_File_Use = open('/home/mwang235/Dropbox/Code/DataSharing/Kw_File_Use.txt', 'rb')
2. f_kw_prime = open('/home/mwang235/Dropbox/Code/DataSharing/kw_prime.txt', 'wb')

**Comment by 123alikaha** [comment]
I have installed all the basic library Pypbc GMP SSL and other documentation but the code is incomplete and unable to run big issues.

**Comment by Wujianting** [comment]
> I have installed all the basic library Pypbc GMP SSL and other documentation but the code is incomplete and unable to run big issues.

Hello, I would like to ask if the code is missing some files at present? Do you know which documents are missing? Has your code run successfully?
你好，我想请问一下目前代码是缺少一些文件吗？具体缺少哪些文件您了解吗？您代码目前已经运行成功了吗？
